name: Run Tests

#
# Create some files with script/new-artifact.sh and confirm they are properly packaged and uploaded
# as artifacts with the actions.
#
# This is tested on all OS platforms where we have hosted runners.
#

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate files
      run: mkdir artifact && mkdir artifact2 && mkdir artifact4 && cd artifact && ../script/new-artifact.sh && cd .. && cp -R artifact artifact3
      shell: bash

    - name: Upload Pages artifact
      uses: ./
      with:
        name: pages-artifact-${{ matrix.os }}
        path: artifact

    - name: Upload Pages artifact overriding the exlusion pattern
      uses: ./
      with:
        name: pages-artifact-override-${{ matrix.os }}
        path: artifact3
        exclude-pattern: ..

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
          name: pages-artifact-${{ matrix.os }}
          path: artifact2
 
    - name: Download artifact overridden exclusion pattern
      uses: actions/download-artifact@v4
      with:
          name: pages-artifact-override-${{ matrix.os }}
          path: artifact4

    - name: Extract artifact
      run: tar -xf artifact2/artifact.tar -C artifact2 && rm artifact2/artifact.tar
      shell: bash

    - name: Extract artifact overridden
      run: tar -xf artifact4/artifact.tar -C artifact4 && rm artifact4/artifact.tar
      shell: bash
    - name: Compare files overriddent
      run: |
        diff -qr artifact3 artifact4
      shell: bash

    - name: Check for absence of hidden files
      run: if [ $(find artifact2 -regex ".*/\..*" | wc -l) != 0 ]; then echo "Hidden files found"; exit 1; fi
      shell: bash

    - name: Compare files
      run: |
        rm artifact/.hidden
        rm -r -f artifact/.hidden2
        diff -qr artifact artifact2
      shell: bash

    - name: Check for absence of symlinks
      run: if [ $(find artifact2 -type l | wc -l) != 0 ]; then echo "Symlinks found"; exit 1; fi
      shell: bash
